Explicit parent class used for ItemComponent (#89)
HasItemComponents.ItemComponent<T> is used. Otherwise NoClassDefFoundError is thrown on a class loading phase.